import type { Metadata } from "next";
import { Poppins, Roboto, Comfortaa } from 'next/font/google'

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/footer";
import { Providers } from "./providers";

 
const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})

const poppins = Poppins({
  weight: ['400', '700', '200', '500', '100'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
})

const comfortaa = Comfortaa({
  weight: ['400', '700', '500', '600'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-comfortaa',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${poppins.variable} ${comfortaa.variable} antialiased `}
      >
        <Providers>
        <main className="max-w-[1440px] mx-auto bg-white">
        <Header />
        {children}
        <Footer /> 
        </main>
        </Providers>
      </body>
    </html>
  );
}
